
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/brews
    username: username
    password: password
  jpa:
    database: POSTGRESQL

discord:
  webhook:
    url: env-variable
